### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by muschellij2** [StreamlineDataScience/gcloud#2]
- [ ] Create a script that takes in a YAML, which has a default set of things to set in the metadata, such as the zone, the project name, etc.
- [ ] Should create the project from `gcloud projects create`?  I'm not sure about that one - may want some of the defaults from the click button
- [ ] It should then provision an R Jupyter notebook VM and run the RStudio Installer
- [ ] It should copy the commands needed to run the RStudio Server from the command line from an S3 bucket
- [ ] It should put that insetance on a schedule (may need to create schedule beforehand so we can then add a tag to the instance, see https://cloud.google.com/compute/docs/instances/schedule-instance-start-stop
> gcloud compute resource-policies create instance-schedule SCHEDULE_NAME \
    [--description='SCHEDULE_DESCRIPTION'] \
    [--region=REGION] \
    [--vm-start-schedule='START-OPERATION_SCHEDULE'] \
    [--vm-stop-schedule='STOP-OPERATION_SCHEDULE'] \
    [--timezone=TIME_ZONE] \
    [--initiation-date=INITIATION_DATE] \
    [--end-date=END_DATE]
- [ ] It should create the nat and have a function that's like "Create R VM", or "Create VM w/o external IP address"
    - need to get the netorks code from https://cloud.google.com/notebooks/docs/images#deciding for the instance

**Comment by muschellij2** [comment]
So what we need a script to do (still):
1) Run notebook - need to grab specific image/family - use data-raw to make a copy of those potential uses for match.arg
   - install RStudio and expose port
   - Remove the external IP
2) Set up a NAT automatically on a new project.  Need to check if one exists already

**Comment by muschellij2** [comment]
Chicken and egg problem with gcloud projects create, so no.

**Comment by muschellij2** [comment]
Order:
create router
create nat
Make notebook
Make Rstudio firewall (probably not actually)
remove external IP
SCP the system.file sh file
Run the command to setup the RStudio Server
Print out terminal command to run
